[package]
name = "hearth-ctl"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
hearth-core = { workspace = true }
hearth-ipc = { workspace = true }
hearth-types = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.24", features = ["macros", "net", "rt", "signal"] }
