name: Pull Request Checks

on:
  workflow_run:
    workflows: ["Update Depgraph"]
    branches: [main]
    types:
      - completed
  push:
    branches: [ "main" ]
    paths:
      - "**/Cargo.toml"
      - "**.rs"
      - ".github/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/Cargo.toml"
      - "**.rs"
      - ".github/**"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-targets
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Swatinem/rust-cache@v2.2.0
    - run: rustup component add clippy
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        override: true
    - uses: LoliGothick/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        flags: --all
