name: Pull Request Checks

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/Cargo.toml"
      - "**.rs"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/Cargo.toml"
      - "**.rs"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets
  wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Install wasm32-unknown-unknown target
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
    - name: Build Wasm test
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: >
          --target wasm32-unknown-unknown -p hearth-test-wasm
          --manifest-path guest/rust/Cargo.toml
    - name: Run Wasm
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: >
          --release -p hearth-cognito --example run_wasm
          -- guest/rust/target/wasm32-unknown-unknown/debug/hearth_test_wasm.wasm
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-targets
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Swatinem/rust-cache@v2.2.0
    - run: rustup component add clippy
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        override: true
    - uses: LoliGothick/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        flags: --all
